version: '3.8'

services:
  frontend:
    container_name: frontend_yummi
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - HOSTNAME=0.0.0.0
    user: "1001"
    restart: always
    volumes:
      - .next_cache:/app/.next/cache
    deploy:
      resources:
        limits:
          memory: 512M  # Limit memory usage to 512MB
        reservations:
          memory: 256M  # Reserve 256MB of memory

volumes:
  .next_cache:
